# Created 2025-06-23 Mon 12:44
#+title: Number Theory
#+author: Jesse Oldroyd
* <2025-06-23 Mon>
The mathematical basis for the cryptographic systems we looked at was modular
arithmetic.  This type of arithmetic is based on computing remainders, and so
prime numbers play an essential part here.

Perhaps the two most important facts we use when working with modular
arithmetic are the following: modular arithmetic respects regular addition;
and modular arithmetic respects regular multiplication.  Both facts follow
from the division algorithm.

*Example*: Let $n$ be a nonnegative integer and let $a = b\mod n$ and $c =
   d\mod n$.  Show that $a+c = b+d \mod n$.

/Answer/: Remainders!

When we looked at RSA public key cryptography, we needed to be able to find
two integers $e$ and $d$ such that $ed = 1 \mod \phi$.  If you look at the
code we used for that, we only required that $\gcd(e, \phi) = 1$.  In
particular, if two numbers have no common factors aside from $1$, then we can
find this "modular inverse."

*Example*: Find $3^{-1}\mod 8$ and $4^{-1}\mod 6$ if possible.

The existence of these inverses can be proved in general using /Bezout's
Identity/, which states the following:
#+begin_quote
If $a,b$ are integers and $\gcd(a,b) = d$, then there exist integers $r,s$
such that $ra+sb = d$.
#+end_quote
