# Created 2025-06-25 Wed 12:56
#+title: Number Theory
#+author: Jesse Oldroyd
* <2025-06-24 Tue>
The mathematical basis for the cryptographic systems we looked at was modular
arithmetic.  This type of arithmetic is based on computing remainders, and so
prime numbers play an essential part here.

Perhaps the two most important facts we use when working with modular
arithmetic are the following: modular arithmetic respects regular addition;
and modular arithmetic respects regular multiplication.  Both facts follow
from the division algorithm.

*Example*: Let $n$ be a nonnegative integer and let $a = b\mod n$ and $c =
   d\mod n$.  Show that $a+c = b+d \mod n$.

/Answer/: Remainders!
* <2025-06-25 Wed>
When we looked at RSA public key cryptography, we needed to be able to find
two integers $e$ and $d$ such that $ed = 1 \mod \phi$.  If you look at the
code we used for that, we only required that $\gcd(e, \phi) = 1$.  In
particular, if two numbers have no common factors aside from $1$, then we can
find this "modular inverse."

*Example*: Find $3^{-1}\mod 8$ and $4^{-1}\mod 6$ if possible.

The existence of these inverses can be proved in general using /Bezout's
Identity/, which states the following:
#+begin_quote
If $a,b$ are integers and $\gcd(a,b) = d$, then there exist integers $r,s$
such that $ra+sb = d$.
#+end_quote

Inverses can be used to solve /congruence equations/ of the form $ax = b\mod
  n$.

*Example*: Solve the following congruences for $x$:
1. $5x = 8 \mod 9$.
2. $4x - 5 = 12 \mod 7$.
3. $6x = 8 \mod 10$.
4. $6x = 7 \mod 10$.

*Example*: An *affine cipher* is a cipher of the form $ax + b \mod 26$, where
$x\in \mathbb{Z}_26$.  This is a generalization of the Caesar cipher, which is
an affine cipher with $a = 1$.  Suppose we decide to set up our own affine
cipher.  What should be true about $a$?

We can set up addition and multiplication tables for $\mathbb{Z}_n$, but these
don't behave quite the same way as multiplication tables for the integers.

*Example*: Set up multiplication tables for $\mathbb{Z}_5$ and
 $\mathbb{Z}_{26}$.  Feel free to use Python to handle any modular arithmetic
 for you!

*Example*: What are all possible powers of the elements of $\mathbb{Z}_5$?
